image: ubuntu:22.04

pipelines:
  default:
    - step:
        name: Self-hosted echo test
        runs-on:
          - self.hosted
        script:
          - echo "SELF-HOSTED RUNNER OK"
          - hostname
          - whoami
          - pwd
          - date